name: brain-sync (dispatch)

on:
  repository_dispatch:
    types: [brain-sync]

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine WORKER_BASE
        run: |
          set -e
          if [ -n "${{ vars.WORKER_BASE }}" ]; then
            echo "WORKER_BASE=${{ vars.WORKER_BASE }}" >> $GITHUB_ENV
          else
            echo "WORKER_BASE=https://kg-brain.mindsparked-channel.workers.dev" >> $GITHUB_ENV
          fi
          echo "Using WORKER_BASE=$WORKER_BASE"

      - name: Fetch brain payloads
        run: |
          set -e
          mkdir -p brain
          curl -sSf "$WORKER_BASE/api/v1/status"          -o brain/status.json
          curl -sSf "$WORKER_BASE/api/v1/context"         -o brain/context.md
          curl -sSf "$WORKER_BASE/api/v1/tasks/summary"   -o brain/tasks_summary.json
          curl -sSf "$WORKER_BASE/api/v1/tasks?state=inbox" -o brain/tasks_inbox.json
          curl -sSf "$WORKER_BASE/api/v1/tasks?state=done"  -o brain/tasks_done.json

      - name: Commit only on diff
        run: |
          set -e
          git config user.name  "kg-site bot"
          git config user.email "kg-site-bot@users.noreply.github.com"
          if [ -z "$(git status --porcelain brain)" ]; then
            echo "No changes in brain/* – skipping commit."
            exit 0
          fi
          git add brain
          ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          git commit -m "brain-sync: update brain/* at ${ts}"
          git push
