name: brain-sync (dispatch)
on:
  repository_dispatch:
    types: [brain-sync]

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      BASE: ${{ vars.WORKER_BASE }}
    steps:
      - uses: actions/checkout@v4
      - name: Set BASE fallback
        run: |
          set -e
          if [ -z "$BASE" ]; then
            BASE="https://kg-brain.mindsparked-channel.workers.dev"
          fi
          echo "BASE=$BASE" >> $GITHUB_ENV
      - name: Fetch brain artifacts
        run: |
          set -e
          mkdir -p brain
          fetch() { curl -fsSL "$1" -o "$2" || true; }
          fetch "$BASE/api/v1/status"            brain/status.json
          fetch "$BASE/api/v1/context"           brain/context.md
          fetch "$BASE/api/v1/tasks/summary"     brain/tasks_summary.json
          fetch "$BASE/api/v1/tasks?state=inbox" brain/tasks_inbox.json
          fetch "$BASE/api/v1/tasks?state=done"  brain/tasks_done.json
          [ -s brain/status.json ]        || echo "{}"  > brain/status.json
          [ -s brain/context.md ]         || echo "# context" > brain/context.md
          [ -s brain/tasks_summary.json ] || echo "{}"  > brain/tasks_summary.json
          [ -s brain/tasks_inbox.json ]   || echo "[]"  > brain/tasks_inbox.json
          [ -s brain/tasks_done.json ]    || echo "[]"  > brain/tasks_done.json
      - name: Commit if changed
        run: |
          git config user.name "kg-bot"
          git config user.email "kg-bot@users.noreply.github.com"
          git add -A brain
          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi
          git commit -m "chore(site): sync brain artifacts (repository_dispatch)"
          git push
