name: health-alert
on:
  workflow_dispatch:
  push:
    paths:
      - "brain/health.json"
jobs:
  check-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read health.json
        id: h
        run: |
          jq -e '.' brain/health.json >/dev/null
          OK=$(jq -r '.ok' brain/health.json)
          TS=$(jq -r '.ts' brain/health.json)
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          AGE_MIN=$(( ( $(date -ud "$NOW" +%s) - $(date -ud "$TS" +%s) ) / 60 ))
          echo "ok=$OK" >> $GITHUB_OUTPUT
          echo "age_min=$AGE_MIN" >> $GITHUB_OUTPUT
      - name: Trigger private repo alert (if bad or stale)
        if: ${{ steps.h.outputs.ok == 'false' || steps.h.outputs.age_min > 20 }}
        env:
          OWNER: mindsparkedchannel
          REPO: karrieregenie-command-center
          TOKEN: ${{ secrets.GITHUB_TOKEN_PRIVATE_FOR_SITE }}
        run: |
          PAY='{ "event_type":"health_alert", "client_payload": { "ok":"'${{ steps.h.outputs.ok }}'", "age_min":'${{ steps.h.outputs.age_min }}', "source":"kg-site" } }'
          curl -sS -X POST \
            -H "Authorization: token ${TOKEN}" \
            -H 'Accept: application/vnd.github+json' \
            https://api.github.com/repos/${OWNER}/${REPO}/dispatches \
            -d "$PAY"