name: smoke-alert
on:
  workflow_dispatch:
  push:
    paths:
      - "brain/smoke.json"
jobs:
  check-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read smoke.json
        id: smoke
        run: |
          jq -e '.' brain/smoke.json >/dev/null
          TS=$(jq -r '.ts' brain/smoke.json)
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          AGE_MIN=$(( ( $(date -ud "$NOW" +%s) - $(date -ud "$TS" +%s) ) / 60 ))
          echo "age_min=$AGE_MIN" >> $GITHUB_OUTPUT
      - name: Trigger private repo alert (if stale)
        if: ${{ steps.smoke.outputs.age_min > 90 }}
        env:
          OWNER: mindsparkedchannel
          REPO: karrieregenie-command-center
          TOKEN: ${{ secrets.GITHUB_TOKEN_PRIVATE_FOR_SITE }}
        run: |
          PAY='{ "event_type":"smoke_alert", "client_payload": { "age_min":'${{ steps.smoke.outputs.age_min }}', "source":"kg-site" } }'
          curl -sS -X POST \
            -H "Authorization: token ${TOKEN}" \
            -H 'Accept: application/vnd.github+json' \
            https://api.github.com/repos/${OWNER}/${REPO}/dispatches \
            -d "$PAY"